pg-master:
  restart: always
  image: aukhan/postgresql:10
  container_name: pg-master
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - DB_USER=root
    - DB_PASS=password
    - DB_NAME=test_db
    - DB_TEMPLATE=

    - DB_EXTENSION=

    - REPLICATION_MODE=master
    - REPLICATION_USER=replicator
    - REPLICATION_PASS=replpassword
    - REPLICATION_SSLMODE=

pg-slave:
  restart: always
  image: aukhan/postgresql:10
  container_name: pg-slave
  ports:
    - "5433:5433"
  links:
    - "PG-master:master"
  environment:
    - DEBUG=false

    - REPLICATION_MODE=slave
    - REPLICATION_HOST=master
    - REPLICATION_USER=replicator
    - REPLICATION_PASS=replpassword
    - REPLICATION_SSLMODE=
  # To persist data you need to create a local dir
  # /srv/docker/postgresql so it can be mapped to the container
  # volumes:
  #   - /srv/docker/postgresql:/var/lib/postgresql
